import type { Plugin } from 'vite';
import { marked } from 'marked';
import matter from 'gray-matter';
import fs from 'fs';
import path from 'path';

export interface BlogPost {
  slug: string;
  title: string;
  date: string;
  category: string;
  tags: string[];
  excerpt: string;
  readTimeMin: number;
  coverImage?: string;
  featured: boolean;
  url: string;
}

export function blogPlugin(): Plugin {
  let isBuild = false;
  const contentDir = path.resolve(process.cwd(), 'src/content/blog');
  const dataDir = path.resolve(process.cwd(), 'src/data');
  const blogTemplatePath = path.resolve(process.cwd(), 'blog/post-template.html');
  
  // Store generated HTML pages across hooks
  const postHtmlMap = new Map<string, { meta: BlogPost; content: string }>();

  // Ensure directories exist
  if (!fs.existsSync(dataDir)) {
    fs.mkdirSync(dataDir, { recursive: true });
  }

  return {
    name: 'vite-plugin-blog',
    configResolved(config) {
      isBuild = config.command === 'build';
    },
    buildStart() {
      const posts: BlogPost[] = [];
      postHtmlMap.clear();

      if (fs.existsSync(contentDir)) {
        const files = fs.readdirSync(contentDir).filter((f: string) => f.endsWith('.md'));

        for (const file of files) {
          const filePath = path.join(contentDir, file);
          const fileContent = fs.readFileSync(filePath, 'utf-8');
          const { data, content } = matter(fileContent);
          
          const wordCount = content.split(/\s+/).length;
          const readTimeMin = Math.max(1, Math.ceil(wordCount / 200));
          const slug = data.slug || file.replace(/\.md$/, '');

          const post: BlogPost = {
            slug: slug as string,
            title: (data.title || 'Untitled') as string,
            date: (data.date ? new Date(data.date).toISOString().split('T')[0] : new Date().toISOString().split('T')[0]) as string,
            category: (data.category || 'Uncategorized') as string,
            tags: (data.tags || []) as string[],
            excerpt: (data.excerpt || content.substring(0, 150) + '...') as string,
            readTimeMin: readTimeMin as number,
            coverImage: data.coverImage as string | undefined,
            featured: !!data.featured as boolean,
            url: `/blog/${slug}/`,
          };

          posts.push(post);
          
          // Render HTML for later
          postHtmlMap.set(slug, { meta: post, content: marked.parse(content) as string });
        }
      }

      // Sort posts by date descending
      posts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

      // Write src/data/blog.ts
      const tsContent = `// Auto-generated by blog-plugin.ts
export interface BlogPost {
  slug: string;
  title: string;
  date: string;
  category: string;
  tags: string[];
  excerpt: string;
  readTimeMin: number;
  coverImage?: string;
  featured: boolean;
  url: string;
}

export const blogPosts: BlogPost[] = ${JSON.stringify(posts, null, 2)};
`;
      fs.writeFileSync(path.join(dataDir, 'blog.ts'), tsContent, 'utf-8');
    },
    
    generateBundle() {
      if (!isBuild) return;
      
      let template = '';
      try {
        template = fs.readFileSync(blogTemplatePath, 'utf-8');
      } catch (e) {
        // Fallback simple template
        template = `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><!--TITLE--></title>
  <meta name="description" content="<!--EXCERPT-->">
  <link rel="stylesheet" href="/assets/main.css">
</head>
<body class="bg-[--color-background] text-[--color-text] font-body antialiased">
  <header class="h-16 border-b border-border flex items-center mb-8">
    <div class="max-w-3xl mx-auto px-6 w-full flex items-center justify-between">
      <a href="/blog/" class="font-mono font-bold tracking-tight text-accent hover:underline">← Back to Blog</a>
    </div>
  </header>
  <div class="max-w-3xl mx-auto pb-20 px-6 prose prose-invert prose-a:text-accent hover:prose-a:text-accent/80">
    <h1 class="text-4xl font-display font-bold mb-4"><!--TITLE--></h1>
    <div class="text-muted mb-8 font-mono text-sm"><!--DATE--> • <!--READTIME--> min read</div>
    <!--CONTENT-->
  </div>
</body>
</html>`;
      }

      for (const [slug, { meta, content }] of postHtmlMap.entries()) {
        const html = template
          .replace(/<!--TITLE-->/g, meta.title)
          .replace(/<!--EXCERPT-->/g, meta.excerpt)
          .replace(/<!--DATE-->/g, meta.date)
          .replace(/<!--READTIME-->/g, meta.readTimeMin.toString())
          .replace(/<!--CONTENT-->/g, content);

        this.emitFile({
          type: 'asset',
          fileName: `blog/${slug}/index.html`,
          source: html
        });
      }
    }
  };
}
