// Auto-generated by blog-plugin.ts
export interface BlogPost {
  slug: string;
  title: string;
  date: string;
  category: string;
  tags: string[];
  excerpt: string;
  readTimeMin: number;
  coverImage?: string;
  featured: boolean;
  url: string;
}

export const blogPosts: BlogPost[] = [
  {
    "slug": "automating-cyberark-python",
    "title": "Automating CyberArk Configurations with Python",
    "date": "2026-06-05",
    "category": "Automation",
    "tags": [
      "CyberArk",
      "Python",
      "PAM",
      "REST API"
    ],
    "excerpt": "How I reduced multivendor configuration processing time from 24 hours to under 15 minutes using async Python and the CyberArk REST API.",
    "readTimeMin": 2,
    "featured": true,
    "url": "/blog/automating-cyberark-python/"
  },
  {
    "slug": "practical-ai-agents-security",
    "title": "Building Practical AI Agents for Security Workflows",
    "date": "2026-06-01",
    "category": "AI",
    "tags": [
      "AI Agents",
      "Security Workflows",
      "LLMs",
      "Automation"
    ],
    "excerpt": "Exploring how multi-agent architectures can orchestrate complex security data gathering and analysis tasks, bridging the gap between chat interfaces and actionable operations.",
    "readTimeMin": 2,
    "featured": true,
    "url": "/blog/practical-ai-agents-security/"
  }
];
